CREATE DATABASE IF NOT EXISTS `todo`;

USE `todo`;

CREATE TABLE IF NOT EXISTS `WORK` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `WORK_NAME` VARCHAR(256) NOT NULL UNIQUE,
    `STARTING_DATE` TIMESTAMP NULL DEFAULT NULL,
    `ENDING_DATE` TIMESTAMP NULL DEFAULT NULL,
    `STATUS` VARCHAR(20),
    `DELETED` TINYINT(1) NOT NULL DEFAULT '0',
    `CREATED_BY` BIGINT(20) NOT NULL,
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` BIGINT(20) NOT NULL,
    `UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
